DEFAULT_CHUNK_SIZE = 1200
DEFAULT_CHUNK_OVERLAP = 100
DEFAULT_TOP_K = 40
DEFAULT_CHUNK_TOP_K = 20
DEFAULT_MAX_TOKENS = 30000
DEFAULT_MAX_GLEANING = 1
DEFAULT_ENTITY_TYPES = ["organization", "person", "event", "location", "concept", "technology", "product"]
DEFAULT_SUMMARY_MAX_TOKENS = 1200
DEFAULT_SUMMARY_CONTEXT_SIZE = 4000
DEFAULT_COSINE_THRESHOLD = 0.4
DEFAULT_RELATED_CHUNK_NUMBER = 5
DEFAULT_MIN_RERANK_SCORE = 0.0
DEFAULT_LLM_TIMEOUT = 180
DEFAULT_EMBEDDING_TIMEOUT = 30
DEFAULT_MAX_PARALLEL = 10

GRAPH_FIELD_SEP = "<SEP>"
